; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35225.0 

	TITLE	C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\integer-parsing\reference\coff\windows-msvc\x86\main.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_s_ascii_digit_bias
EXTRN	_s_digits:BYTE
CONST	SEGMENT
_s_ascii_digit_bias DD FLAT:_s_digits-192
CONST	ENDS
PUBLIC	_parse_decimal
PUBLIC	_main
EXTRN	_puts:PROC
_DATA	SEGMENT
$SG10026 DB	'0', 00H
	ORG $+2
$SG10028 DB	'123', 00H
$SG10030 DB	'65535', 00H
	ORG $+2
$SG10031 DB	'All tests passed.', 00H
_DATA	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\integer-parsing\src\main.c
; Line 22
	push	ebp
	mov	ebp, esp
; Line 23
	push	OFFSET $SG10026
	call	_parse_decimal
	add	esp, 4
	test	eax, eax
	je	SHORT $LN2@main
; Line 24
	mov	eax, 1
	jmp	SHORT $LN1@main
$LN2@main:
; Line 26
	push	OFFSET $SG10028
	call	_parse_decimal
	add	esp, 4
	cmp	eax, 123				; 0000007bH
	je	SHORT $LN3@main
; Line 27
	mov	eax, 2
	jmp	SHORT $LN1@main
$LN3@main:
; Line 29
	push	OFFSET $SG10030
	call	_parse_decimal
	add	esp, 4
	cmp	eax, 65535				; 0000ffffH
	je	SHORT $LN4@main
; Line 30
	mov	eax, 3
	jmp	SHORT $LN1@main
$LN4@main:
; Line 33
	push	OFFSET $SG10031
	call	_puts
	add	esp, 4
; Line 34
	xor	eax, eax
$LN1@main:
; Line 35
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_value$ = -4						; size = 4
_s$ = 8							; size = 4
_parse_decimal PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\integer-parsing\src\main.c
; Line 11
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 12
	mov	DWORD PTR _value$[ebp], 0
$LN2@parse_deci:
; Line 14
	mov	eax, DWORD PTR _s$[ebp]
	movsx	ecx, BYTE PTR [eax]
	test	ecx, ecx
	je	SHORT $LN3@parse_deci
; Line 15
	imul	edx, DWORD PTR _value$[ebp], 10
	mov	eax, DWORD PTR _s$[ebp]
	movzx	ecx, BYTE PTR [eax]
	mov	eax, DWORD PTR _s_ascii_digit_bias
	add	edx, DWORD PTR [eax+ecx*4]
	mov	DWORD PTR _value$[ebp], edx
; Line 16
	mov	ecx, DWORD PTR _s$[ebp]
	add	ecx, 1
	mov	DWORD PTR _s$[ebp], ecx
; Line 17
	jmp	SHORT $LN2@parse_deci
$LN3@parse_deci:
; Line 19
	mov	eax, DWORD PTR _value$[ebp]
; Line 20
	mov	esp, ebp
	pop	ebp
	ret	0
_parse_decimal ENDP
_TEXT	ENDS
END
