; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35225.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	freelist_init
PUBLIC	freelist_alloc
PUBLIC	freelist_free
EXTRN	memset:PROC
pdata	SEGMENT
$pdata$freelist_init DD imagerel $LN3
	DD	imagerel $LN3+40
	DD	imagerel $unwind$freelist_init
$pdata$freelist_alloc DD imagerel $LN9
	DD	imagerel $LN9+177
	DD	imagerel $unwind$freelist_alloc
$pdata$freelist_free DD imagerel $LN8
	DD	imagerel $LN8+274
	DD	imagerel $unwind$freelist_free
$pdata$align_up DD imagerel align_up
	DD	imagerel align_up+47
	DD	imagerel $unwind$align_up
$pdata$chunk_length DD imagerel chunk_length
	DD	imagerel chunk_length+61
	DD	imagerel $unwind$chunk_length
$pdata$chunk_is_used DD imagerel chunk_is_used
	DD	imagerel chunk_is_used+45
	DD	imagerel $unwind$chunk_is_used
$pdata$chunk_set_used DD imagerel chunk_set_used
	DD	imagerel chunk_set_used+57
	DD	imagerel $unwind$chunk_set_used
$pdata$chunk_write DD imagerel chunk_write
	DD	imagerel chunk_write+85
	DD	imagerel $unwind$chunk_write
$pdata$chunk_split DD imagerel chunk_split
	DD	imagerel chunk_split+130
	DD	imagerel $unwind$chunk_split
pdata	ENDS
xdata	SEGMENT
$unwind$freelist_init DD 010e01H
	DD	0420eH
$unwind$freelist_alloc DD 010e01H
	DD	0620eH
$unwind$freelist_free DD 010e01H
	DD	0820eH
$unwind$align_up DD 010901H
	DD	02209H
$unwind$chunk_length DD 010901H
	DD	02209H
$unwind$chunk_is_used DD 010901H
	DD	02209H
$unwind$chunk_set_used DD 010d01H
	DD	0420dH
$unwind$chunk_write DD 011801H
	DD	02218H
$unwind$chunk_split DD 010e01H
	DD	0620eH
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
new_len$ = 32
new_chunk$ = 40
chunk$ = 64
requested$ = 72
chunk_split PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 39
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 40
	mov	rax, QWORD PTR requested$[rsp]
	mov	rcx, QWORD PTR chunk$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR new_chunk$[rsp], rax
; Line 41
	mov	rcx, QWORD PTR chunk$[rsp]
	call	chunk_length
	sub	rax, QWORD PTR requested$[rsp]
	mov	QWORD PTR new_len$[rsp], rax
; Line 44
	cmp	QWORD PTR new_len$[rsp], 32		; 00000020H
	jae	SHORT $LN2@chunk_spli
; Line 45
	jmp	SHORT $LN1@chunk_spli
$LN2@chunk_spli:
; Line 48
	xor	r9d, r9d
	mov	r8, QWORD PTR new_len$[rsp]
	mov	rax, QWORD PTR chunk$[rsp]
	mov	rdx, QWORD PTR [rax]
	mov	rcx, QWORD PTR new_chunk$[rsp]
	call	chunk_write
; Line 49
	mov	rcx, QWORD PTR chunk$[rsp]
	call	chunk_is_used
	mov	r9d, eax
	mov	r8, QWORD PTR requested$[rsp]
	mov	rdx, QWORD PTR new_chunk$[rsp]
	mov	rcx, QWORD PTR chunk$[rsp]
	call	chunk_write
	npad	1
$LN1@chunk_spli:
; Line 50
	add	rsp, 56					; 00000038H
	ret	0
chunk_split ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
ptr$ = 8
chunk_from_data PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 35
	mov	QWORD PTR [rsp+8], rcx
; Line 36
	mov	rax, QWORD PTR ptr$[rsp]
	sub	rax, 16
; Line 37
	ret	0
chunk_from_data ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
chunk$ = 8
chunk_to_data PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 31
	mov	QWORD PTR [rsp+8], rcx
; Line 32
	mov	rax, QWORD PTR chunk$[rsp]
	add	rax, 16
; Line 33
	ret	0
chunk_to_data ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv68 = 0
chunk$ = 32
next$ = 40
length$ = 48
used$ = 56
chunk_write PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 26
	mov	DWORD PTR [rsp+32], r9d
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 27
	mov	rax, QWORD PTR chunk$[rsp]
	mov	rcx, QWORD PTR next$[rsp]
	mov	QWORD PTR [rax], rcx
; Line 28
	cmp	DWORD PTR used$[rsp], 0
	je	SHORT $LN3@chunk_writ
	mov	rax, QWORD PTR length$[rsp]
	neg	rax
	mov	QWORD PTR tv68[rsp], rax
	jmp	SHORT $LN4@chunk_writ
$LN3@chunk_writ:
	mov	rax, QWORD PTR length$[rsp]
	mov	QWORD PTR tv68[rsp], rax
$LN4@chunk_writ:
	mov	rax, QWORD PTR chunk$[rsp]
	mov	rcx, QWORD PTR tv68[rsp]
	mov	QWORD PTR [rax+8], rcx
; Line 29
	add	rsp, 24
	ret	0
chunk_write ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
chunk$ = 48
used$ = 56
chunk_set_used PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 18
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 19
	mov	rcx, QWORD PTR chunk$[rsp]
	call	chunk_is_used
	cmp	eax, DWORD PTR used$[rsp]
	jne	SHORT $LN2@chunk_set_
; Line 20
	jmp	SHORT $LN1@chunk_set_
$LN2@chunk_set_:
; Line 23
	mov	rax, QWORD PTR chunk$[rsp]
	mov	rax, QWORD PTR [rax+8]
	neg	rax
	mov	rcx, QWORD PTR chunk$[rsp]
	mov	QWORD PTR [rcx+8], rax
$LN1@chunk_set_:
; Line 24
	add	rsp, 40					; 00000028H
	ret	0
chunk_set_used ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv66 = 0
chunk$ = 32
chunk_is_used PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 14
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 15
	mov	rax, QWORD PTR chunk$[rsp]
	cmp	QWORD PTR [rax+8], 0
	jge	SHORT $LN3@chunk_is_u
	mov	DWORD PTR tv66[rsp], 1
	jmp	SHORT $LN4@chunk_is_u
$LN3@chunk_is_u:
	mov	DWORD PTR tv66[rsp], 0
$LN4@chunk_is_u:
	mov	eax, DWORD PTR tv66[rsp]
; Line 16
	add	rsp, 24
	ret	0
chunk_is_used ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 0
chunk$ = 32
chunk_length PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 10
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 11
	mov	rax, QWORD PTR chunk$[rsp]
	cmp	QWORD PTR [rax+8], 0
	jle	SHORT $LN3@chunk_leng
	mov	rax, QWORD PTR chunk$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR tv69[rsp], rax
	jmp	SHORT $LN4@chunk_leng
$LN3@chunk_leng:
	mov	rax, QWORD PTR chunk$[rsp]
	mov	rax, QWORD PTR [rax+8]
	neg	rax
	mov	QWORD PTR tv69[rsp], rax
$LN4@chunk_leng:
	mov	rax, QWORD PTR tv69[rsp]
; Line 12
	add	rsp, 24
	ret	0
chunk_length ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
m$ = 0
value$ = 32
align_up PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 5
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 6
	mov	QWORD PTR m$[rsp], 7
; Line 7
	mov	rax, QWORD PTR m$[rsp]
	mov	rcx, QWORD PTR value$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	rcx, QWORD PTR m$[rsp]
	not	rcx
	and	rax, rcx
; Line 8
	add	rsp, 24
	ret	0
align_up ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
chunk$ = 32
tv87 = 40
old_next$1 = 48
heap$ = 80
ptr$ = 88
freelist_free PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 82
$LN8:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
; Line 85
	cmp	QWORD PTR ptr$[rsp], 0
	jne	SHORT $LN4@freelist_f
; Line 86
	jmp	$LN1@freelist_f
$LN4@freelist_f:
; Line 90
	mov	rcx, QWORD PTR ptr$[rsp]
	call	chunk_from_data
	mov	QWORD PTR chunk$[rsp], rax
; Line 91
	xor	edx, edx
	mov	rcx, QWORD PTR chunk$[rsp]
	call	chunk_set_used
; Line 92
	mov	rcx, QWORD PTR chunk$[rsp]
	call	chunk_length
	sub	rax, 16
	mov	r8, rax
	xor	edx, edx
	mov	rcx, QWORD PTR ptr$[rsp]
	call	memset
; Line 95
	mov	rax, QWORD PTR heap$[rsp]
	mov	QWORD PTR chunk$[rsp], rax
$LN2@freelist_f:
; Line 96
	cmp	QWORD PTR chunk$[rsp], 0
	je	$LN3@freelist_f
	mov	rax, QWORD PTR chunk$[rsp]
	cmp	QWORD PTR [rax], 0
	je	$LN3@freelist_f
; Line 97
	mov	rcx, QWORD PTR chunk$[rsp]
	call	chunk_is_used
	test	eax, eax
	jne	SHORT $LN5@freelist_f
	mov	rax, QWORD PTR chunk$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	chunk_is_used
	test	eax, eax
	jne	SHORT $LN5@freelist_f
; Line 98
	mov	rax, QWORD PTR chunk$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR old_next$1[rsp], rax
; Line 100
	mov	rcx, QWORD PTR chunk$[rsp]
	call	chunk_length
	mov	QWORD PTR tv87[rsp], rax
	mov	rcx, QWORD PTR chunk$[rsp]
	mov	rcx, QWORD PTR [rcx]
	call	chunk_length
	mov	rcx, QWORD PTR tv87[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	rcx, QWORD PTR chunk$[rsp]
	mov	rcx, QWORD PTR [rcx]
	xor	r9d, r9d
	mov	r8, rax
	mov	rdx, QWORD PTR [rcx]
	mov	rcx, QWORD PTR chunk$[rsp]
	call	chunk_write
; Line 101
	mov	r8d, 16
	xor	edx, edx
	mov	rcx, QWORD PTR old_next$1[rsp]
	call	memset
	npad	1
; Line 102
	jmp	SHORT $LN6@freelist_f
$LN5@freelist_f:
; Line 103
	mov	rax, QWORD PTR chunk$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR chunk$[rsp], rax
$LN6@freelist_f:
; Line 105
	jmp	$LN2@freelist_f
$LN3@freelist_f:
$LN1@freelist_f:
; Line 106
	add	rsp, 72					; 00000048H
	ret	0
freelist_free ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
cur$ = 32
requested$ = 40
heap$ = 64
size$ = 72
freelist_alloc PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 56
$LN9:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 57
	mov	rcx, QWORD PTR size$[rsp]
	call	align_up
	add	rax, 16
	mov	QWORD PTR requested$[rsp], rax
; Line 60
	cmp	QWORD PTR size$[rsp], 0
	jne	SHORT $LN5@freelist_a
; Line 61
	xor	eax, eax
	jmp	SHORT $LN1@freelist_a
$LN5@freelist_a:
; Line 65
	cmp	QWORD PTR requested$[rsp], 32		; 00000020H
	jae	SHORT $LN6@freelist_a
; Line 66
	mov	QWORD PTR requested$[rsp], 32		; 00000020H
$LN6@freelist_a:
; Line 70
	mov	rax, QWORD PTR heap$[rsp]
	mov	QWORD PTR cur$[rsp], rax
	jmp	SHORT $LN4@freelist_a
$LN2@freelist_a:
	mov	rax, QWORD PTR cur$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR cur$[rsp], rax
$LN4@freelist_a:
	cmp	QWORD PTR cur$[rsp], 0
	je	SHORT $LN3@freelist_a
; Line 71
	mov	rcx, QWORD PTR cur$[rsp]
	call	chunk_is_used
	test	eax, eax
	jne	SHORT $LN7@freelist_a
	mov	rcx, QWORD PTR cur$[rsp]
	call	chunk_length
	cmp	rax, QWORD PTR requested$[rsp]
	jb	SHORT $LN7@freelist_a
; Line 72
	mov	rdx, QWORD PTR requested$[rsp]
	mov	rcx, QWORD PTR cur$[rsp]
	call	chunk_split
; Line 73
	mov	edx, 1
	mov	rcx, QWORD PTR cur$[rsp]
	call	chunk_set_used
; Line 75
	mov	rcx, QWORD PTR cur$[rsp]
	call	chunk_to_data
	jmp	SHORT $LN1@freelist_a
$LN7@freelist_a:
; Line 77
	jmp	SHORT $LN2@freelist_a
$LN3@freelist_a:
; Line 79
	xor	eax, eax
$LN1@freelist_a:
; Line 80
	add	rsp, 56					; 00000038H
	ret	0
freelist_alloc ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
heap$ = 48
heap_size$ = 56
freelist_init PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 52
$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 53
	xor	r9d, r9d
	mov	r8, QWORD PTR heap_size$[rsp]
	xor	edx, edx
	mov	rcx, QWORD PTR heap$[rsp]
	call	chunk_write
	npad	1
; Line 54
	add	rsp, 40					; 00000028H
	ret	0
freelist_init ENDP
_TEXT	ENDS
END
