; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35225.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	s_snapshot_1
PUBLIC	s_snapshot_2
PUBLIC	s_snapshot_3
PUBLIC	s_snapshot_4
PUBLIC	s_snapshot_5
PUBLIC	s_heap_ranges
_DATA	SEGMENT
COMM	s_heap:BYTE:0180H
_DATA	ENDS
CONST	SEGMENT
s_snapshot_1 DQ	0000000000000000H
	DQ	0000000000000180H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
s_snapshot_2 DQ	FLAT:s_heap+32
	DQ	ffffffffffffffe0H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DQ	FLAT:s_heap+64
	DQ	ffffffffffffffe0H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DQ	FLAT:s_heap+96
	DQ	ffffffffffffffe0H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DQ	FLAT:s_heap+128
	DQ	ffffffffffffffe0H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DQ	FLAT:s_heap+192
	DQ	ffffffffffffffc0H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DQ	FLAT:s_heap+256
	DQ	ffffffffffffffc0H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DB	06H
	DQ	FLAT:s_heap+320
	DQ	ffffffffffffffc0H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DQ	0000000000000000H
	DQ	ffffffffffffffc0H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
	DB	08H
s_snapshot_3 DQ	FLAT:s_heap+32
	DQ	ffffffffffffffe0H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DQ	FLAT:s_heap+64
	DQ	0000000000000020H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DQ	FLAT:s_heap+96
	DQ	ffffffffffffffe0H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DB	03H
	DQ	FLAT:s_heap+128
	DQ	0000000000000020H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DQ	FLAT:s_heap+192
	DQ	ffffffffffffffc0H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DQ	FLAT:s_heap+256
	DQ	0000000000000040H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DQ	FLAT:s_heap+320
	DQ	ffffffffffffffc0H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DB	07H
	DQ	0000000000000000H
	DQ	0000000000000040H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
s_snapshot_4 DQ	FLAT:s_heap+32
	DQ	ffffffffffffffe0H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DQ	FLAT:s_heap+128
	DQ	0000000000000060H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	ORG $+16
	DQ	FLAT:s_heap+192
	DQ	ffffffffffffffc0H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DB	05H
	DQ	0000000000000000H
	DQ	00000000000000c0H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
s_snapshot_5 DQ	0000000000000000H
	DQ	0000000000000180H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
s_heap_ranges DQ FLAT:s_snapshot_1
	DQ	FLAT:s_snapshot_1+384
	DQ	FLAT:s_snapshot_2
	DQ	FLAT:s_snapshot_2+384
	DQ	FLAT:s_snapshot_3
	DQ	FLAT:s_snapshot_3+384
	DQ	FLAT:s_snapshot_4
	DQ	FLAT:s_snapshot_4+384
	DQ	FLAT:s_snapshot_5
	DQ	FLAT:s_snapshot_5+384
CONST	ENDS
PUBLIC	main
EXTRN	freelist_init:PROC
EXTRN	freelist_alloc:PROC
EXTRN	freelist_free:PROC
EXTRN	puts:PROC
EXTRN	memcmp:PROC
EXTRN	memset:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__security_cookie:QWORD
pdata	SEGMENT
$pdata$allocate_and_fill DD imagerel allocate_and_fill
	DD	imagerel allocate_and_fill+97
	DD	imagerel $unwind$allocate_and_fill
$pdata$main DD	imagerel $LN22
	DD	imagerel $LN22+837
	DD	imagerel $unwind$main
pdata	ENDS
_DATA	SEGMENT
$SG10588 DB	'All tests passed.', 00H
_DATA	ENDS
voltbl	SEGMENT
_volmd	DD	0ffffffffH
	DDSymXIndex: 	FLAT:main
	DD	011H
	DD	032dH
voltbl	ENDS
xdata	SEGMENT
$unwind$allocate_and_fill DD 011301H
	DD	06213H
$unwind$main DD	021919H
	DD	0130107H
	DD	imagerel __GSHandlerCheck
	DD	080H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
ret$ = 32
i$ = 40
heap$ = 48
tv90 = 56
allocations$ = 64
__$ArrayPad$ = 128
main	PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\main.c
; Line 218
$LN22:
	sub	rsp, 152				; 00000098H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 219
	lea	rax, OFFSET FLAT:s_heap
	mov	QWORD PTR heap$[rsp], rax
; Line 225
	mov	edx, 384				; 00000180H
	mov	rcx, QWORD PTR heap$[rsp]
	call	freelist_init
; Line 227
	mov	eax, 16
	imul	rax, rax, 0
	lea	rcx, OFFSET FLAT:s_heap_ranges
	mov	edx, 16
	imul	rdx, rdx, 0
	lea	r8, OFFSET FLAT:s_heap_ranges
	mov	rdx, QWORD PTR [r8+rdx]
	mov	rax, QWORD PTR [rcx+rax+8]
	sub	rax, rdx
	mov	ecx, 16
	imul	rcx, rcx, 0
	lea	rdx, OFFSET FLAT:s_heap_ranges
	mov	r8, rax
	mov	rdx, QWORD PTR [rdx+rcx]
	mov	rcx, QWORD PTR heap$[rsp]
	call	memcmp
	mov	DWORD PTR ret$[rsp], eax
; Line 228
	cmp	DWORD PTR ret$[rsp], 0
	je	SHORT $LN14@main
; Line 229
	mov	eax, DWORD PTR ret$[rsp]
	jmp	$LN1@main
$LN14@main:
; Line 233
	mov	QWORD PTR i$[rsp], 0
	jmp	SHORT $LN4@main
$LN2@main:
	mov	rax, QWORD PTR i$[rsp]
	inc	rax
	mov	QWORD PTR i$[rsp], rax
$LN4@main:
	cmp	QWORD PTR i$[rsp], 8
	jae	SHORT $LN3@main
; Line 234
	cmp	QWORD PTR i$[rsp], 4
	jae	SHORT $LN20@main
	mov	DWORD PTR tv90[rsp], 32			; 00000020H
	jmp	SHORT $LN21@main
$LN20@main:
	mov	DWORD PTR tv90[rsp], 64			; 00000040H
$LN21@main:
	mov	rax, QWORD PTR i$[rsp]
	inc	rax
	movsxd	rcx, DWORD PTR tv90[rsp]
	movzx	r8d, al
	mov	rdx, rcx
	mov	rcx, QWORD PTR heap$[rsp]
	call	allocate_and_fill
	mov	rcx, QWORD PTR i$[rsp]
	mov	QWORD PTR allocations$[rsp+rcx*8], rax
; Line 235
	jmp	SHORT $LN2@main
$LN3@main:
; Line 237
	mov	eax, 16
	imul	rax, rax, 1
	lea	rcx, OFFSET FLAT:s_heap_ranges
	mov	edx, 16
	imul	rdx, rdx, 1
	lea	r8, OFFSET FLAT:s_heap_ranges
	mov	rdx, QWORD PTR [r8+rdx]
	mov	rax, QWORD PTR [rcx+rax+8]
	sub	rax, rdx
	mov	ecx, 16
	imul	rcx, rcx, 1
	lea	rdx, OFFSET FLAT:s_heap_ranges
	mov	r8, rax
	mov	rdx, QWORD PTR [rdx+rcx]
	mov	rcx, QWORD PTR heap$[rsp]
	call	memcmp
	mov	DWORD PTR ret$[rsp], eax
; Line 238
	cmp	DWORD PTR ret$[rsp], 0
	je	SHORT $LN15@main
; Line 239
	mov	eax, DWORD PTR ret$[rsp]
	jmp	$LN1@main
$LN15@main:
; Line 243
	mov	QWORD PTR i$[rsp], 1
	jmp	SHORT $LN7@main
$LN5@main:
	mov	rax, QWORD PTR i$[rsp]
	add	rax, 2
	mov	QWORD PTR i$[rsp], rax
$LN7@main:
	cmp	QWORD PTR i$[rsp], 8
	jae	SHORT $LN6@main
; Line 244
	mov	rax, QWORD PTR i$[rsp]
	mov	rdx, QWORD PTR allocations$[rsp+rax*8]
	mov	rcx, QWORD PTR heap$[rsp]
	call	freelist_free
	npad	1
; Line 245
	jmp	SHORT $LN5@main
$LN6@main:
; Line 247
	mov	eax, 16
	imul	rax, rax, 2
	lea	rcx, OFFSET FLAT:s_heap_ranges
	mov	edx, 16
	imul	rdx, rdx, 2
	lea	r8, OFFSET FLAT:s_heap_ranges
	mov	rdx, QWORD PTR [r8+rdx]
	mov	rax, QWORD PTR [rcx+rax+8]
	sub	rax, rdx
	mov	ecx, 16
	imul	rcx, rcx, 2
	lea	rdx, OFFSET FLAT:s_heap_ranges
	mov	r8, rax
	mov	rdx, QWORD PTR [rdx+rcx]
	mov	rcx, QWORD PTR heap$[rsp]
	call	memcmp
	mov	DWORD PTR ret$[rsp], eax
; Line 248
	cmp	DWORD PTR ret$[rsp], 0
	je	SHORT $LN16@main
; Line 249
	mov	eax, DWORD PTR ret$[rsp]
	jmp	$LN1@main
$LN16@main:
; Line 253
	mov	QWORD PTR i$[rsp], 2
	jmp	SHORT $LN10@main
$LN8@main:
	mov	rax, QWORD PTR i$[rsp]
	add	rax, 4
	mov	QWORD PTR i$[rsp], rax
$LN10@main:
	cmp	QWORD PTR i$[rsp], 8
	jae	SHORT $LN9@main
; Line 254
	mov	rax, QWORD PTR i$[rsp]
	mov	rdx, QWORD PTR allocations$[rsp+rax*8]
	mov	rcx, QWORD PTR heap$[rsp]
	call	freelist_free
	npad	1
; Line 255
	jmp	SHORT $LN8@main
$LN9@main:
; Line 257
	mov	eax, 16
	imul	rax, rax, 3
	lea	rcx, OFFSET FLAT:s_heap_ranges
	mov	edx, 16
	imul	rdx, rdx, 3
	lea	r8, OFFSET FLAT:s_heap_ranges
	mov	rdx, QWORD PTR [r8+rdx]
	mov	rax, QWORD PTR [rcx+rax+8]
	sub	rax, rdx
	mov	ecx, 16
	imul	rcx, rcx, 3
	lea	rdx, OFFSET FLAT:s_heap_ranges
	mov	r8, rax
	mov	rdx, QWORD PTR [rdx+rcx]
	mov	rcx, QWORD PTR heap$[rsp]
	call	memcmp
	mov	DWORD PTR ret$[rsp], eax
; Line 258
	cmp	DWORD PTR ret$[rsp], 0
	je	SHORT $LN17@main
; Line 259
	mov	eax, DWORD PTR ret$[rsp]
	jmp	$LN1@main
$LN17@main:
; Line 263
	mov	QWORD PTR i$[rsp], 0
	jmp	SHORT $LN13@main
$LN11@main:
	mov	rax, QWORD PTR i$[rsp]
	add	rax, 4
	mov	QWORD PTR i$[rsp], rax
$LN13@main:
	cmp	QWORD PTR i$[rsp], 8
	jae	SHORT $LN12@main
; Line 264
	mov	rax, QWORD PTR i$[rsp]
	mov	rdx, QWORD PTR allocations$[rsp+rax*8]
	mov	rcx, QWORD PTR heap$[rsp]
	call	freelist_free
	npad	1
; Line 265
	jmp	SHORT $LN11@main
$LN12@main:
; Line 267
	mov	eax, 16
	imul	rax, rax, 4
	lea	rcx, OFFSET FLAT:s_heap_ranges
	mov	edx, 16
	imul	rdx, rdx, 4
	lea	r8, OFFSET FLAT:s_heap_ranges
	mov	rdx, QWORD PTR [r8+rdx]
	mov	rax, QWORD PTR [rcx+rax+8]
	sub	rax, rdx
	mov	ecx, 16
	imul	rcx, rcx, 4
	lea	rdx, OFFSET FLAT:s_heap_ranges
	mov	r8, rax
	mov	rdx, QWORD PTR [rdx+rcx]
	mov	rcx, QWORD PTR heap$[rsp]
	call	memcmp
	mov	DWORD PTR ret$[rsp], eax
; Line 268
	cmp	DWORD PTR ret$[rsp], 0
	jne	SHORT $LN18@main
; Line 269
	lea	rcx, OFFSET FLAT:$SG10588
	call	puts
	npad	1
$LN18@main:
; Line 272
	mov	eax, DWORD PTR ret$[rsp]
$LN1@main:
; Line 273
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 152				; 00000098H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
ptr$ = 32
heap$ = 64
size$ = 72
pattern$ = 80
allocate_and_fill PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\main.c
; Line 207
	mov	BYTE PTR [rsp+24], r8b
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 208
	mov	rax, QWORD PTR size$[rsp]
	sub	rax, 16
	mov	rdx, rax
	mov	rcx, QWORD PTR heap$[rsp]
	call	freelist_alloc
	mov	QWORD PTR ptr$[rsp], rax
; Line 210
	cmp	QWORD PTR ptr$[rsp], 0
	jne	SHORT $LN2@allocate_a
; Line 211
	xor	eax, eax
	jmp	SHORT $LN1@allocate_a
$LN2@allocate_a:
; Line 214
	mov	rax, QWORD PTR size$[rsp]
	sub	rax, 16
	movzx	ecx, BYTE PTR pattern$[rsp]
	mov	r8, rax
	mov	edx, ecx
	mov	rcx, QWORD PTR ptr$[rsp]
	call	memset
; Line 215
	mov	rax, QWORD PTR ptr$[rsp]
$LN1@allocate_a:
; Line 216
	add	rsp, 56					; 00000038H
	ret	0
allocate_and_fill ENDP
_TEXT	ENDS
END
