; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35225.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_openbsd_ctype_
CONST	SEGMENT
_openbsd_ctype_ DB 00H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	028H
	DB	028H
	DB	028H
	DB	028H
	DB	028H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	088H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	041H
	DB	041H
	DB	041H
	DB	041H
	DB	041H
	DB	041H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	042H
	DB	042H
	DB	042H
	DB	042H
	DB	042H
	DB	042H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	020H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
CONST	ENDS
PUBLIC	openbsd_isalnum
PUBLIC	openbsd_isalpha
PUBLIC	openbsd_iscntrl
PUBLIC	openbsd_isdigit
PUBLIC	openbsd_isgraph
PUBLIC	openbsd_islower
PUBLIC	openbsd_isprint
PUBLIC	openbsd_ispunct
PUBLIC	openbsd_isspace
PUBLIC	openbsd_isupper
PUBLIC	openbsd_isxdigit
pdata	SEGMENT
$pdata$openbsd_isalnum DD imagerel $LN5
	DD	imagerel $LN5+55
	DD	imagerel $unwind$openbsd_isalnum
$pdata$openbsd_isalpha DD imagerel $LN5
	DD	imagerel $LN5+55
	DD	imagerel $unwind$openbsd_isalpha
$pdata$openbsd_iscntrl DD imagerel $LN5
	DD	imagerel $LN5+55
	DD	imagerel $unwind$openbsd_iscntrl
$pdata$openbsd_isdigit DD imagerel $LN5
	DD	imagerel $LN5+55
	DD	imagerel $unwind$openbsd_isdigit
$pdata$openbsd_isgraph DD imagerel $LN5
	DD	imagerel $LN5+55
	DD	imagerel $unwind$openbsd_isgraph
$pdata$openbsd_islower DD imagerel $LN5
	DD	imagerel $LN5+55
	DD	imagerel $unwind$openbsd_islower
$pdata$openbsd_isprint DD imagerel $LN5
	DD	imagerel $LN5+57
	DD	imagerel $unwind$openbsd_isprint
$pdata$openbsd_ispunct DD imagerel $LN5
	DD	imagerel $LN5+55
	DD	imagerel $unwind$openbsd_ispunct
$pdata$openbsd_isspace DD imagerel $LN5
	DD	imagerel $LN5+55
	DD	imagerel $unwind$openbsd_isspace
$pdata$openbsd_isupper DD imagerel $LN5
	DD	imagerel $LN5+55
	DD	imagerel $unwind$openbsd_isupper
$pdata$openbsd_isxdigit DD imagerel $LN5
	DD	imagerel $LN5+55
	DD	imagerel $unwind$openbsd_isxdigit
pdata	ENDS
xdata	SEGMENT
$unwind$openbsd_isalnum DD 010801H
	DD	02208H
$unwind$openbsd_isalpha DD 010801H
	DD	02208H
$unwind$openbsd_iscntrl DD 010801H
	DD	02208H
$unwind$openbsd_isdigit DD 010801H
	DD	02208H
$unwind$openbsd_isgraph DD 010801H
	DD	02208H
$unwind$openbsd_islower DD 010801H
	DD	02208H
$unwind$openbsd_isprint DD 010801H
	DD	02208H
$unwind$openbsd_ispunct DD 010801H
	DD	02208H
$unwind$openbsd_isspace DD 010801H
	DD	02208H
$unwind$openbsd_isupper DD 010801H
	DD	02208H
$unwind$openbsd_isxdigit DD 010801H
	DD	02208H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = 0
_c$ = 32
openbsd_isxdigit PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 137
$LN5:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 138
	cmp	DWORD PTR _c$[rsp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[rsp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	lea	rax, OFFSET FLAT:_openbsd_ctype_
	movzx	ecx, BYTE PTR _c$[rsp]
	movsx	eax, BYTE PTR [rax+rcx+1]
	and	eax, 68					; 00000044H
	mov	DWORD PTR tv71[rsp], eax
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[rsp]
; Line 139
	add	rsp, 24
	ret	0
openbsd_isxdigit ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = 0
_c$ = 32
openbsd_isupper PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 132
$LN5:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 133
	cmp	DWORD PTR _c$[rsp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[rsp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	lea	rax, OFFSET FLAT:_openbsd_ctype_
	movzx	ecx, BYTE PTR _c$[rsp]
	movsx	eax, BYTE PTR [rax+rcx+1]
	and	eax, 1
	mov	DWORD PTR tv71[rsp], eax
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[rsp]
; Line 134
	add	rsp, 24
	ret	0
openbsd_isupper ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = 0
_c$ = 32
openbsd_isspace PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 127
$LN5:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 128
	cmp	DWORD PTR _c$[rsp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[rsp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	lea	rax, OFFSET FLAT:_openbsd_ctype_
	movzx	ecx, BYTE PTR _c$[rsp]
	movsx	eax, BYTE PTR [rax+rcx+1]
	and	eax, 8
	mov	DWORD PTR tv71[rsp], eax
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[rsp]
; Line 129
	add	rsp, 24
	ret	0
openbsd_isspace ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = 0
_c$ = 32
openbsd_ispunct PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 122
$LN5:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 123
	cmp	DWORD PTR _c$[rsp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[rsp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	lea	rax, OFFSET FLAT:_openbsd_ctype_
	movzx	ecx, BYTE PTR _c$[rsp]
	movsx	eax, BYTE PTR [rax+rcx+1]
	and	eax, 16
	mov	DWORD PTR tv71[rsp], eax
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[rsp]
; Line 124
	add	rsp, 24
	ret	0
openbsd_ispunct ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = 0
_c$ = 32
openbsd_isprint PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 117
$LN5:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 118
	cmp	DWORD PTR _c$[rsp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[rsp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	lea	rax, OFFSET FLAT:_openbsd_ctype_
	movzx	ecx, BYTE PTR _c$[rsp]
	movsx	eax, BYTE PTR [rax+rcx+1]
	and	eax, 151				; 00000097H
	mov	DWORD PTR tv71[rsp], eax
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[rsp]
; Line 119
	add	rsp, 24
	ret	0
openbsd_isprint ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = 0
_c$ = 32
openbsd_islower PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 112
$LN5:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 113
	cmp	DWORD PTR _c$[rsp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[rsp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	lea	rax, OFFSET FLAT:_openbsd_ctype_
	movzx	ecx, BYTE PTR _c$[rsp]
	movsx	eax, BYTE PTR [rax+rcx+1]
	and	eax, 2
	mov	DWORD PTR tv71[rsp], eax
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[rsp]
; Line 114
	add	rsp, 24
	ret	0
openbsd_islower ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = 0
_c$ = 32
openbsd_isgraph PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 107
$LN5:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 108
	cmp	DWORD PTR _c$[rsp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[rsp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	lea	rax, OFFSET FLAT:_openbsd_ctype_
	movzx	ecx, BYTE PTR _c$[rsp]
	movsx	eax, BYTE PTR [rax+rcx+1]
	and	eax, 23
	mov	DWORD PTR tv71[rsp], eax
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[rsp]
; Line 109
	add	rsp, 24
	ret	0
openbsd_isgraph ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = 0
_c$ = 32
openbsd_isdigit PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 102
$LN5:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 103
	cmp	DWORD PTR _c$[rsp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[rsp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	lea	rax, OFFSET FLAT:_openbsd_ctype_
	movzx	ecx, BYTE PTR _c$[rsp]
	movsx	eax, BYTE PTR [rax+rcx+1]
	and	eax, 4
	mov	DWORD PTR tv71[rsp], eax
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[rsp]
; Line 104
	add	rsp, 24
	ret	0
openbsd_isdigit ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = 0
_c$ = 32
openbsd_iscntrl PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 97
$LN5:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 98
	cmp	DWORD PTR _c$[rsp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[rsp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	lea	rax, OFFSET FLAT:_openbsd_ctype_
	movzx	ecx, BYTE PTR _c$[rsp]
	movsx	eax, BYTE PTR [rax+rcx+1]
	and	eax, 32					; 00000020H
	mov	DWORD PTR tv71[rsp], eax
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[rsp]
; Line 99
	add	rsp, 24
	ret	0
openbsd_iscntrl ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = 0
_c$ = 32
openbsd_isalpha PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 92
$LN5:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 93
	cmp	DWORD PTR _c$[rsp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[rsp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	lea	rax, OFFSET FLAT:_openbsd_ctype_
	movzx	ecx, BYTE PTR _c$[rsp]
	movsx	eax, BYTE PTR [rax+rcx+1]
	and	eax, 3
	mov	DWORD PTR tv71[rsp], eax
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[rsp]
; Line 94
	add	rsp, 24
	ret	0
openbsd_isalpha ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = 0
_c$ = 32
openbsd_isalnum PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 87
$LN5:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 88
	cmp	DWORD PTR _c$[rsp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[rsp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	lea	rax, OFFSET FLAT:_openbsd_ctype_
	movzx	ecx, BYTE PTR _c$[rsp]
	movsx	eax, BYTE PTR [rax+rcx+1]
	and	eax, 7
	mov	DWORD PTR tv71[rsp], eax
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[rsp]
; Line 89
	add	rsp, 24
	ret	0
openbsd_isalnum ENDP
_TEXT	ENDS
END
