; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35225.0 

	TITLE	C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\reference\coff\windows-msvc\x86\openbsd_ctype.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	__openbsd_ctype_
CONST	SEGMENT
__openbsd_ctype_ DB 00H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	028H
	DB	028H
	DB	028H
	DB	028H
	DB	028H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	020H
	DB	088H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	04H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	041H
	DB	041H
	DB	041H
	DB	041H
	DB	041H
	DB	041H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	01H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	042H
	DB	042H
	DB	042H
	DB	042H
	DB	042H
	DB	042H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	02H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	020H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
CONST	ENDS
PUBLIC	_openbsd_isalnum
PUBLIC	_openbsd_isalpha
PUBLIC	_openbsd_iscntrl
PUBLIC	_openbsd_isdigit
PUBLIC	_openbsd_isgraph
PUBLIC	_openbsd_islower
PUBLIC	_openbsd_isprint
PUBLIC	_openbsd_ispunct
PUBLIC	_openbsd_isspace
PUBLIC	_openbsd_isupper
PUBLIC	_openbsd_isxdigit
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = -4						; size = 4
__c$ = 8						; size = 4
_openbsd_isxdigit PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 137
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 138
	cmp	DWORD PTR __c$[ebp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[ebp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	movzx	eax, BYTE PTR __c$[ebp]
	movsx	ecx, BYTE PTR __openbsd_ctype_[eax+1]
	and	ecx, 68					; 00000044H
	mov	DWORD PTR tv71[ebp], ecx
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[ebp]
; Line 139
	mov	esp, ebp
	pop	ebp
	ret	0
_openbsd_isxdigit ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = -4						; size = 4
__c$ = 8						; size = 4
_openbsd_isupper PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 132
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 133
	cmp	DWORD PTR __c$[ebp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[ebp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	movzx	eax, BYTE PTR __c$[ebp]
	movsx	ecx, BYTE PTR __openbsd_ctype_[eax+1]
	and	ecx, 1
	mov	DWORD PTR tv71[ebp], ecx
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[ebp]
; Line 134
	mov	esp, ebp
	pop	ebp
	ret	0
_openbsd_isupper ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = -4						; size = 4
__c$ = 8						; size = 4
_openbsd_isspace PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 127
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 128
	cmp	DWORD PTR __c$[ebp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[ebp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	movzx	eax, BYTE PTR __c$[ebp]
	movsx	ecx, BYTE PTR __openbsd_ctype_[eax+1]
	and	ecx, 8
	mov	DWORD PTR tv71[ebp], ecx
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[ebp]
; Line 129
	mov	esp, ebp
	pop	ebp
	ret	0
_openbsd_isspace ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = -4						; size = 4
__c$ = 8						; size = 4
_openbsd_ispunct PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 122
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 123
	cmp	DWORD PTR __c$[ebp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[ebp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	movzx	eax, BYTE PTR __c$[ebp]
	movsx	ecx, BYTE PTR __openbsd_ctype_[eax+1]
	and	ecx, 16					; 00000010H
	mov	DWORD PTR tv71[ebp], ecx
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[ebp]
; Line 124
	mov	esp, ebp
	pop	ebp
	ret	0
_openbsd_ispunct ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = -4						; size = 4
__c$ = 8						; size = 4
_openbsd_isprint PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 117
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 118
	cmp	DWORD PTR __c$[ebp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[ebp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	movzx	eax, BYTE PTR __c$[ebp]
	movsx	ecx, BYTE PTR __openbsd_ctype_[eax+1]
	and	ecx, 151				; 00000097H
	mov	DWORD PTR tv71[ebp], ecx
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[ebp]
; Line 119
	mov	esp, ebp
	pop	ebp
	ret	0
_openbsd_isprint ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = -4						; size = 4
__c$ = 8						; size = 4
_openbsd_islower PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 112
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 113
	cmp	DWORD PTR __c$[ebp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[ebp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	movzx	eax, BYTE PTR __c$[ebp]
	movsx	ecx, BYTE PTR __openbsd_ctype_[eax+1]
	and	ecx, 2
	mov	DWORD PTR tv71[ebp], ecx
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[ebp]
; Line 114
	mov	esp, ebp
	pop	ebp
	ret	0
_openbsd_islower ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = -4						; size = 4
__c$ = 8						; size = 4
_openbsd_isgraph PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 107
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 108
	cmp	DWORD PTR __c$[ebp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[ebp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	movzx	eax, BYTE PTR __c$[ebp]
	movsx	ecx, BYTE PTR __openbsd_ctype_[eax+1]
	and	ecx, 23					; 00000017H
	mov	DWORD PTR tv71[ebp], ecx
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[ebp]
; Line 109
	mov	esp, ebp
	pop	ebp
	ret	0
_openbsd_isgraph ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = -4						; size = 4
__c$ = 8						; size = 4
_openbsd_isdigit PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 102
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 103
	cmp	DWORD PTR __c$[ebp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[ebp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	movzx	eax, BYTE PTR __c$[ebp]
	movsx	ecx, BYTE PTR __openbsd_ctype_[eax+1]
	and	ecx, 4
	mov	DWORD PTR tv71[ebp], ecx
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[ebp]
; Line 104
	mov	esp, ebp
	pop	ebp
	ret	0
_openbsd_isdigit ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = -4						; size = 4
__c$ = 8						; size = 4
_openbsd_iscntrl PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 97
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 98
	cmp	DWORD PTR __c$[ebp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[ebp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	movzx	eax, BYTE PTR __c$[ebp]
	movsx	ecx, BYTE PTR __openbsd_ctype_[eax+1]
	and	ecx, 32					; 00000020H
	mov	DWORD PTR tv71[ebp], ecx
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[ebp]
; Line 99
	mov	esp, ebp
	pop	ebp
	ret	0
_openbsd_iscntrl ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = -4						; size = 4
__c$ = 8						; size = 4
_openbsd_isalpha PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 92
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 93
	cmp	DWORD PTR __c$[ebp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[ebp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	movzx	eax, BYTE PTR __c$[ebp]
	movsx	ecx, BYTE PTR __openbsd_ctype_[eax+1]
	and	ecx, 3
	mov	DWORD PTR tv71[ebp], ecx
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[ebp]
; Line 94
	mov	esp, ebp
	pop	ebp
	ret	0
_openbsd_isalpha ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = -4						; size = 4
__c$ = 8						; size = 4
_openbsd_isalnum PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\ascii-table\src\openbsd_ctype.c
; Line 87
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 88
	cmp	DWORD PTR __c$[ebp], -1
	jne	SHORT $LN3@openbsd_is
	mov	DWORD PTR tv71[ebp], 0
	jmp	SHORT $LN4@openbsd_is
$LN3@openbsd_is:
	movzx	eax, BYTE PTR __c$[ebp]
	movsx	ecx, BYTE PTR __openbsd_ctype_[eax+1]
	and	ecx, 7
	mov	DWORD PTR tv71[ebp], ecx
$LN4@openbsd_is:
	mov	eax, DWORD PTR tv71[ebp]
; Line 89
	mov	esp, ebp
	pop	ebp
	ret	0
_openbsd_isalnum ENDP
_TEXT	ENDS
END
