; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.8153 

	TITLE	D:\programming\widberg\ghidra-delinker-extension\src\test\resources\ascii-table\reference\coff_xbox360\powerpcbe\main.c
	.PPC
	.MODEL FLAT
PUBLIC	NUM_ASCII_PROPERTIES
PUBLIC	s_ascii_properties
PUBLIC	COLUMNS
EXTRN	islower:PROC
EXTRN	isupper:PROC
EXTRN	isdigit:PROC
EXTRN	isalpha:PROC
EXTRN	isalnum:PROC
EXTRN	ispunct:PROC
EXTRN	isspace:PROC
EXTRN	iscntrl:PROC
EXTRN	isprint:PROC
EXTRN	isgraph:PROC
	.data
COLUMNS	DD	04H
	.rdata
NUM_ASCII_PROPERTIES DD 0aH
	ORG $+4
s_ascii_properties DD isgraph
	DB	067H
	ORG $+3
	DD	isprint
	DB	070H
	ORG $+3
	DD	iscntrl
	DB	063H
	ORG $+3
	DD	isspace
	DB	073H
	ORG $+3
	DD	ispunct
	DB	021H
	ORG $+3
	DD	isalnum
	DB	041H
	ORG $+3
	DD	isalpha
	DB	061H
	ORG $+3
	DD	isdigit
	DB	064H
	ORG $+3
	DD	isupper
	DB	055H
	ORG $+3
	DD	islower
	DB	06cH
	ORG $+3
PUBLIC	print_number
EXTRN	putchar:PROC
	.pdata
$T2405	DD	print_number
	DD	040002603H
; Function compile flags: /Odtu

	.code
n$ = 80							; size = 4
digit$2370 = 84						; size = 4

print_number PROC NEAR

; Begin code for function: print_number
; File d:\programming\widberg\ghidra-delinker-extension\src\test\resources\ascii-table\reference\coff_xbox360\powerpcbe\main.c
; Line 25
	mflr         r12
	stw          r12,-8(r1)
	stwu         r1,-60h(r1)
.endprolog
$M2403:
	stw          r3,num$(r1)		; 116 (74h)
; Line 28
	li           r11,3
	stw          r11,n$(r1)		; 80 (50h)
	b            $LN5@print_numb
$LN4@print_numb:
	lwz          r10,n$(r1)		; 80 (50h)
	addi         r9,r10,-1		; 0FFFFh
	stw          r9,n$(r1)		; 80 (50h)
$LN5@print_numb:
	lwz          r8,n$(r1)		; 80 (50h)
	cmpwi        cr6,r8,0
	blt          cr6,$LN6@print_numb
; Line 29
	lwz          r7,n$(r1)		; 80 (50h)
	slwi         r6,r7,2
	lwz          r5,num$(r1)		; 116 (74h)
	sraw         r4,r5,r6
	li           r3,16		; 10h
	divw         r11,r4,r3
	slwi         r10,r11,4
	subf         r9,r10,r4
	stw          r9,digit$2370(r1)		; 84 (54h)
; Line 31
	lwz          r8,digit$2370(r1)		; 84 (54h)
	cmpwi        cr6,r8,10		; 0Ah
	bge          cr6,$LN2@print_numb
; Line 32
	lwz          r7,digit$2370(r1)		; 84 (54h)
	addi         r3,r7,48		; 30h
	bl           putchar
; Line 33
	b            $LN1@print_numb
$LN2@print_numb:
; Line 34
	lwz          r6,digit$2370(r1)		; 84 (54h)
	addi         r5,r6,97		; 61h
	addi         r3,r5,-10		; 0FFF6h
	bl           putchar
$LN1@print_numb:
; Line 35
	b            $LN4@print_numb
$LN6@print_numb:
; Line 36
	addi         r1,r1,96		; 60h
	lwz          r12,-8(r1)
	mtlr         r12
	blr
$M2404:
; End code for function: print_number
print_number ENDP

PUBLIC	print_ascii_entry
EXTRN	__pctype_func:PROC
	.pdata
$T2409	DD	print_ascii_entry
	DD	040003f03H
; Function compile flags: /Odtu

	.code
k$ = 80							; size = 4
property$2387 = 84					; size = 4

print_ascii_entry PROC NEAR

; Begin code for function: print_ascii_entry
; Line 38
	mflr         r12
	stw          r12,-8(r1)
	stwu         r1,-60h(r1)
.endprolog
$M2407:
	stb          r3,character$(r1)		; 119 (77h)
	stw          r4,properties$(r1)		; 124 (7Ch)
	stw          r5,num_ascii_properties$(r1)		; 132 (84h)
; Line 41
	lbz          r11,character$(r1)		; 119 (77h)
	extsb        r3,r11
	bl           print_number
; Line 42
	li           r3,32		; 20h
	bl           putchar
; Line 44
	bl           __pctype_func
	lbz          r10,character$(r1)		; 119 (77h)
	extsb        r9,r10
	slwi         r8,r9,1
	lhzx         r7,r3,r8
	li           r12,279		; 117h
	and          r6,r7,r12
	cmpwi        cr6,r6,0
	beq          cr6,$LN7@print_asci
; Line 45
	lbz          r5,character$(r1)		; 119 (77h)
	extsb        r3,r5
	bl           putchar
; Line 46
	b            $LN6@print_asci
$LN7@print_asci:
; Line 47
	li           r3,32		; 20h
	bl           putchar
$LN6@print_asci:
; Line 48
	li           r3,32		; 20h
	bl           putchar
; Line 50
	li           r4,0
	stw          r4,k$(r1)		; 80 (50h)
	b            $LN5@print_asci
$LN4@print_asci:
	lwz          r3,k$(r1)		; 80 (50h)
	addi         r11,r3,1
	stw          r11,k$(r1)		; 80 (50h)
$LN5@print_asci:
	lwz          r10,k$(r1)		; 80 (50h)
	lwz          r9,num_ascii_properties$(r1)		; 132 (84h)
	cmpw         cr6,r10,r9
	bge          cr6,$LN8@print_asci
; Line 51
	lwz          r8,k$(r1)		; 80 (50h)
	slwi         r7,r8,3
	lwz          r6,properties$(r1)		; 124 (7Ch)
	add          r5,r6,r7
	stw          r5,property$2387(r1)		; 84 (54h)
; Line 53
	lbz          r4,character$(r1)		; 119 (77h)
	extsb        r3,r4
	lwz          r11,property$2387(r1)		; 84 (54h)
	lwz          r10,0(r11)
	mtctr        r10
	bctrl
	cmpwi        cr6,r3,0
	beq          cr6,$LN2@print_asci
; Line 54
	lwz          r9,property$2387(r1)		; 84 (54h)
	lbz          r8,4(r9)
	extsb        r3,r8
	bl           putchar
; Line 55
	b            $LN1@print_asci
$LN2@print_asci:
; Line 56
	li           r3,32		; 20h
	bl           putchar
$LN1@print_asci:
; Line 57
	b            $LN4@print_asci
$LN8@print_asci:
; Line 58
	addi         r1,r1,96		; 60h
	lwz          r12,-8(r1)
	mtlr         r12
	blr
$M2408:
; End code for function: print_ascii_entry
print_ascii_entry ENDP

PUBLIC	main
	.pdata
$T2413	DD	main
	DD	040004f03H
; Function compile flags: /Odtu

	.code
i$ = 80							; size = 4
y$2397 = 84						; size = 4
x$2396 = 88						; size = 4
character$2398 = 92					; size = 4

main PROC NEAR

; Begin code for function: main
; Line 60
	mflr         r12
	stw          r12,-8(r1)
	stwu         r1,-70h(r1)
.endprolog
$M2411:
; Line 63
	li           r11,0
	stw          r11,i$(r1)		; 80 (50h)
	b            $LN3@main
$LN2@main:
	lwz          r10,i$(r1)		; 80 (50h)
	addi         r9,r10,1
	stw          r9,i$(r1)		; 80 (50h)
$LN3@main:
	lwz          r8,i$(r1)		; 80 (50h)
	cmpwi        cr6,r8,128		; 80h
	bge          cr6,$LN1@main
; Line 64
	lwz          r7,i$(r1)		; 80 (50h)
	lis          r6,COLUMNS
	lwz          r5,COLUMNS(r6)
	divw         r4,r7,r5
	twllei       r5,0
	rotlwi       r3,r7,1
	addi         r11,r3,-1		; 0FFFFh
	andc         r10,r5,r11
	twlgei       r10,-1		; 0FFFFh
	mullw        r9,r4,r5
	subf         r8,r9,r7
	stw          r8,x$2396(r1)		; 88 (58h)
; Line 65
	lwz          r7,i$(r1)		; 80 (50h)
	lis          r6,COLUMNS
	lwz          r5,COLUMNS(r6)
	divw         r4,r7,r5
	twllei       r5,0
	rotlwi       r3,r7,1
	addi         r11,r3,-1		; 0FFFFh
	andc         r10,r5,r11
	twlgei       r10,-1		; 0FFFFh
	stw          r4,y$2397(r1)		; 84 (54h)
; Line 66
	lwz          r9,x$2396(r1)		; 88 (58h)
	slwi         r8,r9,7
	lis          r7,COLUMNS
	lwz          r6,COLUMNS(r7)
	divw         r5,r8,r6
	twllei       r6,0
	rotlwi       r4,r8,1
	addi         r3,r4,-1		; 0FFFFh
	andc         r11,r6,r3
	twlgei       r11,-1		; 0FFFFh
	lwz          r10,y$2397(r1)		; 84 (54h)
	add          r9,r5,r10
	stw          r9,character$2398(r1)		; 92 (5Ch)
; Line 68
	lis          r8,NUM_ASCII_PROPERTIES
	lwz          r5,NUM_ASCII_PROPERTIES(r8)
	lis          r7,s_ascii_properties
	addi         r4,r7,s_ascii_properties
	lwz          r6,character$2398(r1)		; 92 (5Ch)
	extsb        r3,r6
	bl           print_ascii_entry
; Line 70
	lwz          r5,i$(r1)		; 80 (50h)
	lis          r4,COLUMNS
	lwz          r3,COLUMNS(r4)
	divw         r11,r5,r3
	twllei       r3,0
	rotlwi       r10,r5,1
	addi         r9,r10,-1		; 0FFFFh
	andc         r8,r3,r9
	twlgei       r8,-1		; 0FFFFh
	mullw        r7,r11,r3
	subf         r6,r7,r5
	lis          r5,COLUMNS
	lwz          r4,COLUMNS(r5)
	addi         r3,r4,-1		; 0FFFFh
	subf         r11,r6,r3
	cntlzw       r10,r11
	rlwinm       r9,r10,27,31,31
	addi         r3,r9,9
	bl           putchar
; Line 71
	b            $LN2@main
$LN1@main:
; Line 73
	li           r3,0
; Line 74
	addi         r1,r1,112		; 70h
	lwz          r12,-8(r1)
	mtlr         r12
	blr
$M2412:
; End code for function: main
main	ENDP

END
