; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35225.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	s_digits
CONST	SEGMENT
s_digits DD	00H
	DD	01H
	DD	02H
	DD	03H
	DD	04H
	DD	05H
	DD	06H
	DD	07H
	DD	08H
	DD	09H
CONST	ENDS
END
