; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35225.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	s_ascii_digit_bias
EXTRN	s_digits:BYTE
CONST	SEGMENT
s_ascii_digit_bias DQ FLAT:s_digits-192
CONST	ENDS
PUBLIC	parse_decimal
PUBLIC	main
EXTRN	puts:PROC
pdata	SEGMENT
$pdata$parse_decimal DD imagerel $LN5
	DD	imagerel $LN5+76
	DD	imagerel $unwind$parse_decimal
$pdata$main DD	imagerel $LN6
	DD	imagerel $LN6+96
	DD	imagerel $unwind$main
pdata	ENDS
_DATA	SEGMENT
$SG9924	DB	'0', 00H
	ORG $+2
$SG9926	DB	'123', 00H
$SG9928	DB	'65535', 00H
	ORG $+2
$SG9929	DB	'All tests passed.', 00H
_DATA	ENDS
xdata	SEGMENT
$unwind$parse_decimal DD 010901H
	DD	02209H
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\integer-parsing\src\main.c
; Line 22
$LN6:
	sub	rsp, 40					; 00000028H
; Line 23
	lea	rcx, OFFSET FLAT:$SG9924
	call	parse_decimal
	test	eax, eax
	je	SHORT $LN2@main
; Line 24
	mov	eax, 1
	jmp	SHORT $LN1@main
$LN2@main:
; Line 26
	lea	rcx, OFFSET FLAT:$SG9926
	call	parse_decimal
	cmp	eax, 123				; 0000007bH
	je	SHORT $LN3@main
; Line 27
	mov	eax, 2
	jmp	SHORT $LN1@main
$LN3@main:
; Line 29
	lea	rcx, OFFSET FLAT:$SG9928
	call	parse_decimal
	cmp	eax, 65535				; 0000ffffH
	je	SHORT $LN4@main
; Line 30
	mov	eax, 3
	jmp	SHORT $LN1@main
$LN4@main:
; Line 33
	lea	rcx, OFFSET FLAT:$SG9929
	call	puts
; Line 34
	xor	eax, eax
$LN1@main:
; Line 35
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
value$ = 0
s$ = 32
parse_decimal PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\integer-parsing\src\main.c
; Line 11
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 12
	mov	DWORD PTR value$[rsp], 0
$LN2@parse_deci:
; Line 14
	mov	rax, QWORD PTR s$[rsp]
	movsx	eax, BYTE PTR [rax]
	test	eax, eax
	je	SHORT $LN3@parse_deci
; Line 15
	imul	eax, DWORD PTR value$[rsp], 10
	mov	rcx, QWORD PTR s$[rsp]
	movzx	ecx, BYTE PTR [rcx]
	mov	rdx, QWORD PTR s_ascii_digit_bias
	add	eax, DWORD PTR [rdx+rcx*4]
	mov	DWORD PTR value$[rsp], eax
; Line 16
	mov	rax, QWORD PTR s$[rsp]
	inc	rax
	mov	QWORD PTR s$[rsp], rax
; Line 17
	jmp	SHORT $LN2@parse_deci
$LN3@parse_deci:
; Line 19
	mov	eax, DWORD PTR value$[rsp]
; Line 20
	add	rsp, 24
	ret	0
parse_decimal ENDP
_TEXT	ENDS
END
