; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35225.0 

	TITLE	C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\reference\coff\windows-msvc\x86\allocator.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_freelist_init
PUBLIC	_freelist_alloc
PUBLIC	_freelist_free
EXTRN	_memset:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_new_chunk$ = -8					; size = 4
_new_len$ = -4						; size = 4
_chunk$ = 8						; size = 4
_requested$ = 12					; size = 4
_chunk_split PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 39
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 40
	mov	eax, DWORD PTR _chunk$[ebp]
	add	eax, DWORD PTR _requested$[ebp]
	mov	DWORD PTR _new_chunk$[ebp], eax
; Line 41
	mov	ecx, DWORD PTR _chunk$[ebp]
	push	ecx
	call	_chunk_length
	add	esp, 4
	sub	eax, DWORD PTR _requested$[ebp]
	mov	DWORD PTR _new_len$[ebp], eax
; Line 44
	cmp	DWORD PTR _new_len$[ebp], 16		; 00000010H
	jae	SHORT $LN2@chunk_spli
; Line 45
	jmp	SHORT $LN1@chunk_spli
$LN2@chunk_spli:
; Line 48
	push	0
	mov	edx, DWORD PTR _new_len$[ebp]
	push	edx
	mov	eax, DWORD PTR _chunk$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	mov	edx, DWORD PTR _new_chunk$[ebp]
	push	edx
	call	_chunk_write
	add	esp, 16					; 00000010H
; Line 49
	mov	eax, DWORD PTR _chunk$[ebp]
	push	eax
	call	_chunk_is_used
	add	esp, 4
	push	eax
	mov	ecx, DWORD PTR _requested$[ebp]
	push	ecx
	mov	edx, DWORD PTR _new_chunk$[ebp]
	push	edx
	mov	eax, DWORD PTR _chunk$[ebp]
	push	eax
	call	_chunk_write
	add	esp, 16					; 00000010H
$LN1@chunk_spli:
; Line 50
	mov	esp, ebp
	pop	ebp
	ret	0
_chunk_split ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_ptr$ = 8						; size = 4
_chunk_from_data PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 35
	push	ebp
	mov	ebp, esp
; Line 36
	mov	eax, DWORD PTR _ptr$[ebp]
	sub	eax, 8
; Line 37
	pop	ebp
	ret	0
_chunk_from_data ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_chunk$ = 8						; size = 4
_chunk_to_data PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 31
	push	ebp
	mov	ebp, esp
; Line 32
	mov	eax, DWORD PTR _chunk$[ebp]
	add	eax, 8
; Line 33
	pop	ebp
	ret	0
_chunk_to_data ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv68 = -4						; size = 4
_chunk$ = 8						; size = 4
_next$ = 12						; size = 4
_length$ = 16						; size = 4
_used$ = 20						; size = 4
_chunk_write PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 26
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 27
	mov	eax, DWORD PTR _chunk$[ebp]
	mov	ecx, DWORD PTR _next$[ebp]
	mov	DWORD PTR [eax], ecx
; Line 28
	cmp	DWORD PTR _used$[ebp], 0
	je	SHORT $LN3@chunk_writ
	mov	edx, DWORD PTR _length$[ebp]
	neg	edx
	mov	DWORD PTR tv68[ebp], edx
	jmp	SHORT $LN4@chunk_writ
$LN3@chunk_writ:
	mov	eax, DWORD PTR _length$[ebp]
	mov	DWORD PTR tv68[ebp], eax
$LN4@chunk_writ:
	mov	ecx, DWORD PTR _chunk$[ebp]
	mov	edx, DWORD PTR tv68[ebp]
	mov	DWORD PTR [ecx+4], edx
; Line 29
	mov	esp, ebp
	pop	ebp
	ret	0
_chunk_write ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_chunk$ = 8						; size = 4
_used$ = 12						; size = 4
_chunk_set_used PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 18
	push	ebp
	mov	ebp, esp
; Line 19
	mov	eax, DWORD PTR _chunk$[ebp]
	push	eax
	call	_chunk_is_used
	add	esp, 4
	cmp	eax, DWORD PTR _used$[ebp]
	jne	SHORT $LN2@chunk_set_
; Line 20
	jmp	SHORT $LN1@chunk_set_
$LN2@chunk_set_:
; Line 23
	mov	ecx, DWORD PTR _chunk$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	neg	edx
	mov	eax, DWORD PTR _chunk$[ebp]
	mov	DWORD PTR [eax+4], edx
$LN1@chunk_set_:
; Line 24
	pop	ebp
	ret	0
_chunk_set_used ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv66 = -4						; size = 4
_chunk$ = 8						; size = 4
_chunk_is_used PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 14
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 15
	mov	eax, DWORD PTR _chunk$[ebp]
	cmp	DWORD PTR [eax+4], 0
	jge	SHORT $LN3@chunk_is_u
	mov	DWORD PTR tv66[ebp], 1
	jmp	SHORT $LN4@chunk_is_u
$LN3@chunk_is_u:
	mov	DWORD PTR tv66[ebp], 0
$LN4@chunk_is_u:
	mov	eax, DWORD PTR tv66[ebp]
; Line 16
	mov	esp, ebp
	pop	ebp
	ret	0
_chunk_is_used ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = -4						; size = 4
_chunk$ = 8						; size = 4
_chunk_length PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 10
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 11
	mov	eax, DWORD PTR _chunk$[ebp]
	cmp	DWORD PTR [eax+4], 0
	jle	SHORT $LN3@chunk_leng
	mov	ecx, DWORD PTR _chunk$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	mov	DWORD PTR tv69[ebp], edx
	jmp	SHORT $LN4@chunk_leng
$LN3@chunk_leng:
	mov	eax, DWORD PTR _chunk$[ebp]
	mov	ecx, DWORD PTR [eax+4]
	neg	ecx
	mov	DWORD PTR tv69[ebp], ecx
$LN4@chunk_leng:
	mov	eax, DWORD PTR tv69[ebp]
; Line 12
	mov	esp, ebp
	pop	ebp
	ret	0
_chunk_length ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_m$ = -4						; size = 4
_value$ = 8						; size = 4
_align_up PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 5
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 6
	mov	DWORD PTR _m$[ebp], 3
; Line 7
	mov	eax, DWORD PTR _value$[ebp]
	add	eax, DWORD PTR _m$[ebp]
	mov	ecx, DWORD PTR _m$[ebp]
	not	ecx
	and	eax, ecx
; Line 8
	mov	esp, ebp
	pop	ebp
	ret	0
_align_up ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_old_next$1 = -8					; size = 4
_chunk$ = -4						; size = 4
_heap$ = 8						; size = 4
_ptr$ = 12						; size = 4
_freelist_free PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 82
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	push	esi
; Line 85
	cmp	DWORD PTR _ptr$[ebp], 0
	jne	SHORT $LN4@freelist_f
; Line 86
	jmp	$LN3@freelist_f
$LN4@freelist_f:
; Line 90
	mov	eax, DWORD PTR _ptr$[ebp]
	push	eax
	call	_chunk_from_data
	add	esp, 4
	mov	DWORD PTR _chunk$[ebp], eax
; Line 91
	push	0
	mov	ecx, DWORD PTR _chunk$[ebp]
	push	ecx
	call	_chunk_set_used
	add	esp, 8
; Line 92
	mov	edx, DWORD PTR _chunk$[ebp]
	push	edx
	call	_chunk_length
	add	esp, 4
	sub	eax, 8
	push	eax
	push	0
	mov	eax, DWORD PTR _ptr$[ebp]
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH
; Line 95
	mov	ecx, DWORD PTR _heap$[ebp]
	mov	DWORD PTR _chunk$[ebp], ecx
$LN2@freelist_f:
; Line 96
	cmp	DWORD PTR _chunk$[ebp], 0
	je	$LN3@freelist_f
	mov	edx, DWORD PTR _chunk$[ebp]
	cmp	DWORD PTR [edx], 0
	je	SHORT $LN3@freelist_f
; Line 97
	mov	eax, DWORD PTR _chunk$[ebp]
	push	eax
	call	_chunk_is_used
	add	esp, 4
	test	eax, eax
	jne	SHORT $LN5@freelist_f
	mov	ecx, DWORD PTR _chunk$[ebp]
	mov	edx, DWORD PTR [ecx]
	push	edx
	call	_chunk_is_used
	add	esp, 4
	test	eax, eax
	jne	SHORT $LN5@freelist_f
; Line 98
	mov	eax, DWORD PTR _chunk$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _old_next$1[ebp], ecx
; Line 100
	push	0
	mov	edx, DWORD PTR _chunk$[ebp]
	push	edx
	call	_chunk_length
	add	esp, 4
	mov	esi, eax
	mov	eax, DWORD PTR _chunk$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	call	_chunk_length
	add	esp, 4
	add	esi, eax
	push	esi
	mov	edx, DWORD PTR _chunk$[ebp]
	mov	eax, DWORD PTR [edx]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	mov	edx, DWORD PTR _chunk$[ebp]
	push	edx
	call	_chunk_write
	add	esp, 16					; 00000010H
; Line 101
	push	8
	push	0
	mov	eax, DWORD PTR _old_next$1[ebp]
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH
; Line 102
	jmp	SHORT $LN6@freelist_f
$LN5@freelist_f:
; Line 103
	mov	ecx, DWORD PTR _chunk$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR _chunk$[ebp], edx
$LN6@freelist_f:
; Line 105
	jmp	$LN2@freelist_f
$LN3@freelist_f:
; Line 106
	pop	esi
	mov	esp, ebp
	pop	ebp
	ret	0
_freelist_free ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_requested$ = -8					; size = 4
_cur$ = -4						; size = 4
_heap$ = 8						; size = 4
_size$ = 12						; size = 4
_freelist_alloc PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 56
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 57
	mov	eax, DWORD PTR _size$[ebp]
	push	eax
	call	_align_up
	add	esp, 4
	add	eax, 8
	mov	DWORD PTR _requested$[ebp], eax
; Line 60
	cmp	DWORD PTR _size$[ebp], 0
	jne	SHORT $LN5@freelist_a
; Line 61
	xor	eax, eax
	jmp	SHORT $LN1@freelist_a
$LN5@freelist_a:
; Line 65
	cmp	DWORD PTR _requested$[ebp], 16		; 00000010H
	jae	SHORT $LN6@freelist_a
; Line 66
	mov	DWORD PTR _requested$[ebp], 16		; 00000010H
$LN6@freelist_a:
; Line 70
	mov	ecx, DWORD PTR _heap$[ebp]
	mov	DWORD PTR _cur$[ebp], ecx
	jmp	SHORT $LN4@freelist_a
$LN2@freelist_a:
	mov	edx, DWORD PTR _cur$[ebp]
	mov	eax, DWORD PTR [edx]
	mov	DWORD PTR _cur$[ebp], eax
$LN4@freelist_a:
	cmp	DWORD PTR _cur$[ebp], 0
	je	SHORT $LN3@freelist_a
; Line 71
	mov	ecx, DWORD PTR _cur$[ebp]
	push	ecx
	call	_chunk_is_used
	add	esp, 4
	test	eax, eax
	jne	SHORT $LN7@freelist_a
	mov	edx, DWORD PTR _cur$[ebp]
	push	edx
	call	_chunk_length
	add	esp, 4
	cmp	eax, DWORD PTR _requested$[ebp]
	jb	SHORT $LN7@freelist_a
; Line 72
	mov	eax, DWORD PTR _requested$[ebp]
	push	eax
	mov	ecx, DWORD PTR _cur$[ebp]
	push	ecx
	call	_chunk_split
	add	esp, 8
; Line 73
	push	1
	mov	edx, DWORD PTR _cur$[ebp]
	push	edx
	call	_chunk_set_used
	add	esp, 8
; Line 75
	mov	eax, DWORD PTR _cur$[ebp]
	push	eax
	call	_chunk_to_data
	add	esp, 4
	jmp	SHORT $LN1@freelist_a
$LN7@freelist_a:
; Line 77
	jmp	SHORT $LN2@freelist_a
$LN3@freelist_a:
; Line 79
	xor	eax, eax
$LN1@freelist_a:
; Line 80
	mov	esp, ebp
	pop	ebp
	ret	0
_freelist_alloc ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_heap$ = 8						; size = 4
_heap_size$ = 12					; size = 4
_freelist_init PROC
; File C:\Users\jblbe\Documents\Workspace\ghidra-delinker-extension\src\test\resources\programs\freelist-allocator\src\allocator.c
; Line 52
	push	ebp
	mov	ebp, esp
; Line 53
	push	0
	mov	eax, DWORD PTR _heap_size$[ebp]
	push	eax
	push	0
	mov	ecx, DWORD PTR _heap$[ebp]
	push	ecx
	call	_chunk_write
	add	esp, 16					; 00000010H
; Line 54
	pop	ebp
	ret	0
_freelist_init ENDP
_TEXT	ENDS
END
