; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35215.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	NUM_ASCII_PROPERTIES
PUBLIC	s_ascii_properties
PUBLIC	COLUMNS
EXTRN	isalpha:PROC
EXTRN	isupper:PROC
EXTRN	islower:PROC
EXTRN	isdigit:PROC
EXTRN	isspace:PROC
EXTRN	ispunct:PROC
EXTRN	isalnum:PROC
EXTRN	isprint:PROC
EXTRN	isgraph:PROC
EXTRN	iscntrl:PROC
_DATA	SEGMENT
COLUMNS	DD	04H
_DATA	ENDS
CONST	SEGMENT
NUM_ASCII_PROPERTIES DD 0aH
	ORG $+12
s_ascii_properties DQ FLAT:isgraph
	DB	067H
	ORG $+7
	DQ	FLAT:isprint
	DB	070H
	ORG $+7
	DQ	FLAT:iscntrl
	DB	063H
	ORG $+7
	DQ	FLAT:isspace
	DB	073H
	ORG $+7
	DQ	FLAT:ispunct
	DB	021H
	ORG $+7
	DQ	FLAT:isalnum
	DB	041H
	ORG $+7
	DQ	FLAT:isalpha
	DB	061H
	ORG $+7
	DQ	FLAT:isdigit
	DB	064H
	ORG $+7
	DQ	FLAT:isupper
	DB	055H
	ORG $+7
	DQ	FLAT:islower
	DB	06cH
	ORG $+7
CONST	ENDS
PUBLIC	print_number
PUBLIC	print_ascii_entry
PUBLIC	main
EXTRN	putchar:PROC
pdata	SEGMENT
$pdata$print_number DD imagerel $LN8
	DD	imagerel $LN8+112
	DD	imagerel $unwind$print_number
$pdata$print_ascii_entry DD imagerel $LN10
	DD	imagerel $LN10+203
	DD	imagerel $unwind$print_ascii_entry
$pdata$main DD	imagerel $LN8
	DD	imagerel $LN8+182
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$print_number DD 010801H
	DD	06208H
$unwind$print_ascii_entry DD 011201H
	DD	06212H
$unwind$main DD	010401H
	DD	08204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$ = 32
tv78 = 36
x$1 = 40
y$2 = 44
character$3 = 48
main	PROC
; File D:\programming\widberg\ghidra-delinker-extension\src\test\resources\ascii-table\src\main.c
; Line 60
$LN8:
	sub	rsp, 72					; 00000048H
; Line 63
	mov	DWORD PTR i$[rsp], 0
	jmp	SHORT $LN4@main
$LN2@main:
	mov	eax, DWORD PTR i$[rsp]
	inc	eax
	mov	DWORD PTR i$[rsp], eax
$LN4@main:
	cmp	DWORD PTR i$[rsp], 128			; 00000080H
	jge	$LN3@main
; Line 64
	mov	eax, DWORD PTR i$[rsp]
	cdq
	idiv	DWORD PTR COLUMNS
	mov	eax, edx
	mov	DWORD PTR x$1[rsp], eax
; Line 65
	mov	eax, DWORD PTR i$[rsp]
	cdq
	idiv	DWORD PTR COLUMNS
	mov	DWORD PTR y$2[rsp], eax
; Line 66
	imul	eax, DWORD PTR x$1[rsp], 128		; 00000080H
	cdq
	idiv	DWORD PTR COLUMNS
	add	eax, DWORD PTR y$2[rsp]
	mov	DWORD PTR character$3[rsp], eax
; Line 68
	mov	r8d, DWORD PTR NUM_ASCII_PROPERTIES
	lea	rdx, OFFSET FLAT:s_ascii_properties
	movzx	ecx, BYTE PTR character$3[rsp]
	call	print_ascii_entry
; Line 70
	mov	eax, DWORD PTR i$[rsp]
	cdq
	idiv	DWORD PTR COLUMNS
	mov	eax, edx
	mov	ecx, DWORD PTR COLUMNS
	dec	ecx
	cmp	eax, ecx
	jne	SHORT $LN6@main
	mov	DWORD PTR tv78[rsp], 10
	jmp	SHORT $LN7@main
$LN6@main:
	mov	DWORD PTR tv78[rsp], 9
$LN7@main:
	mov	ecx, DWORD PTR tv78[rsp]
	call	putchar
	npad	1
; Line 71
	jmp	$LN2@main
$LN3@main:
; Line 73
	xor	eax, eax
; Line 74
	add	rsp, 72					; 00000048H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
k$ = 32
property$1 = 40
character$ = 64
properties$ = 72
num_ascii_properties$ = 80
print_ascii_entry PROC
; File D:\programming\widberg\ghidra-delinker-extension\src\test\resources\ascii-table\src\main.c
; Line 38
$LN10:
	mov	DWORD PTR [rsp+24], r8d
	mov	QWORD PTR [rsp+16], rdx
	mov	BYTE PTR [rsp+8], cl
	sub	rsp, 56					; 00000038H
; Line 41
	movsx	eax, BYTE PTR character$[rsp]
	mov	ecx, eax
	call	print_number
; Line 42
	mov	ecx, 32					; 00000020H
	call	putchar
; Line 44
	movsx	eax, BYTE PTR character$[rsp]
	mov	ecx, eax
	call	isgraph
	test	eax, eax
	je	SHORT $LN5@print_asci
; Line 45
	movsx	eax, BYTE PTR character$[rsp]
	mov	ecx, eax
	call	putchar
	npad	1
	jmp	SHORT $LN6@print_asci
$LN5@print_asci:
; Line 47
	mov	ecx, 32					; 00000020H
	call	putchar
	npad	1
$LN6@print_asci:
; Line 48
	mov	ecx, 32					; 00000020H
	call	putchar
	npad	1
; Line 50
	mov	DWORD PTR k$[rsp], 0
	jmp	SHORT $LN4@print_asci
$LN2@print_asci:
	mov	eax, DWORD PTR k$[rsp]
	inc	eax
	mov	DWORD PTR k$[rsp], eax
$LN4@print_asci:
	mov	eax, DWORD PTR num_ascii_properties$[rsp]
	cmp	DWORD PTR k$[rsp], eax
	jge	SHORT $LN3@print_asci
; Line 51
	movsxd	rax, DWORD PTR k$[rsp]
	imul	rax, rax, 16
	mov	rcx, QWORD PTR properties$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR property$1[rsp], rax
; Line 53
	movsx	eax, BYTE PTR character$[rsp]
	mov	ecx, eax
	mov	rax, QWORD PTR property$1[rsp]
	call	QWORD PTR [rax]
	test	eax, eax
	je	SHORT $LN7@print_asci
; Line 54
	mov	rax, QWORD PTR property$1[rsp]
	movsx	eax, BYTE PTR [rax+8]
	mov	ecx, eax
	call	putchar
	npad	1
	jmp	SHORT $LN8@print_asci
$LN7@print_asci:
; Line 56
	mov	ecx, 32					; 00000020H
	call	putchar
	npad	1
$LN8@print_asci:
; Line 57
	jmp	SHORT $LN2@print_asci
$LN3@print_asci:
; Line 58
	add	rsp, 56					; 00000038H
	ret	0
print_ascii_entry ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
n$ = 32
digit$1 = 36
num$ = 64
print_number PROC
; File D:\programming\widberg\ghidra-delinker-extension\src\test\resources\ascii-table\src\main.c
; Line 25
$LN8:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 56					; 00000038H
; Line 28
	mov	DWORD PTR n$[rsp], 3
	jmp	SHORT $LN4@print_numb
$LN2@print_numb:
	mov	eax, DWORD PTR n$[rsp]
	dec	eax
	mov	DWORD PTR n$[rsp], eax
$LN4@print_numb:
	cmp	DWORD PTR n$[rsp], 0
	jl	SHORT $LN3@print_numb
; Line 29
	mov	eax, DWORD PTR n$[rsp]
	shl	eax, 2
	movzx	ecx, al
	mov	eax, DWORD PTR num$[rsp]
	sar	eax, cl
	cdq
	and	edx, 15
	add	eax, edx
	and	eax, 15
	sub	eax, edx
	mov	DWORD PTR digit$1[rsp], eax
; Line 31
	cmp	DWORD PTR digit$1[rsp], 10
	jge	SHORT $LN5@print_numb
; Line 32
	mov	eax, DWORD PTR digit$1[rsp]
	add	eax, 48					; 00000030H
	mov	ecx, eax
	call	putchar
	npad	1
	jmp	SHORT $LN6@print_numb
$LN5@print_numb:
; Line 34
	mov	eax, DWORD PTR digit$1[rsp]
	add	eax, 87					; 00000057H
	mov	ecx, eax
	call	putchar
	npad	1
$LN6@print_numb:
; Line 35
	jmp	SHORT $LN2@print_numb
$LN3@print_numb:
; Line 36
	add	rsp, 56					; 00000038H
	ret	0
print_number ENDP
_TEXT	ENDS
END
